name: flutter_platform_widgets
description: Simplifying the use of both Material and Cupertino widgets with a single widget
version: 7.0.1
homepage: https://github.com/M-Ahal/flutter_platform_widgets
documentation: https://github.com/stryder-dev/flutter_platform_widgets/wiki






environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"






dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8






dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
